# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  tests:
    docker:
      - image: circleci/ruby:2.6.33-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run: bundle exec rspec
  rubocop:
    docker:
      - image: circleci/ruby:2.6.33-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run: bundle exec rubocop --fail-level=refactor
workflows:
  build:
    jobs:
      - tests
      - rubocop
